import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'navy':        '#0A2540',
        'royal-blue':  '#1E3A8A',
        'sky-blue':    '#60A5FA',
        'off-white':   '#F8FAFC',
        'light-blue':  '#EFF6FF',
        'nox-base':          '#F8FAFC',
        'nox-layer':         '#F0F4F8',
        'nox-layer-high':    '#FFFFFF',
        'nox-border':        'rgba(10,37,64,0.10)',
        'nox-border-dim':    'rgba(10,37,64,0.06)',
        'nox-border-active': 'rgba(10,37,64,0.24)',
        'nox-cyan':          '#3B82F6',
        'nox-cyan-dim':      '#2563EB',
        'nox-royal':         '#1D4ED8',
        'nox-navy':          '#0A2540',
        'nox-footer':        '#0A2540',
        'nox-text':          '#0A2540',
        'nox-text-muted':    '#1E3A5F',
        'nox-text-dim':      '#4A6080',
        'surface':                '#F8FAFC',
        'surface-dim':            '#F0F4F8',
        'surface-container':      '#FFFFFF',
        'surface-container-high': '#EFF6FF',
        'on-surface':             '#0A2540',
        'on-surface-variant':     '#1E3A5F',
        'outline':                'rgba(10,37,64,0.10)',
        'outline-variant':        'rgba(10,37,64,0.06)',
        'accent':       '#3B82F6',
        'accent-hover': '#2563EB',
        'accent-soft':  'rgba(59,130,246,0.12)',
        'accent-glow':  'rgba(59,130,246,0.28)',
      },
      fontFamily: {
        sans:  ['Geist', 'system-ui', 'sans-serif'],
        geist: ['Geist', 'system-ui', 'sans-serif'],
        mono:  ['Geist Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display':     ['64px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-md':  ['48px', { lineHeight: '1.08', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-caps':  ['11px', { lineHeight: '1.2', letterSpacing: '0.12em',   fontWeight: '600' }],
        'technical':   ['12px', { lineHeight: '1.4', letterSpacing: '0em',      fontWeight: '400' }],
      },
      spacing: {
        '18':             '72px',
        'desktop-margin': '64px',
        'mobile-margin':  '20px',
        'gutter':         '24px',
      },
      maxWidth: { 'nox': '1440px', 'content': '1200px' },
      borderRadius: {
        DEFAULT: '10px', 'none': '0px', 'sm': '4px', 'md': '8px',
        'lg': '12px', 'xl': '16px', '2xl': '20px', 'card': '16px',
        'button': '10px', 'pill': '9999px',
      },
      animation: {
        'fade-up':     'fadeUp 0.6s ease-out forwards',
        'fade-in':     'fadeIn 0.5s ease-out forwards',
        'pulse-glow':  'pulseGlow 2s ease-in-out infinite',
        'halo-breath': 'haloBreath 4s ease-in-out infinite',
        'word-up':     'wordUp 0.55s cubic-bezier(0.16,1,0.3,1) forwards',
      },
      keyframes: {
        fadeUp:     { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:     { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        pulseGlow:  { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        haloBreath: { '0%, 100%': { opacity: '0.3', transform: 'scale(1)' }, '50%': { opacity: '0.55', transform: 'scale(1.18)' } },
        wordUp:     { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
} satisfies Config;
